### PR TITLE
#485 Support 'app' type for 'widgetNamespace' argument in 'configureE…

### PR DESCRIPTION
**Pull request by electriccode**
Support `app` type for `widgetNamespace` argument in `configureEntryEditor` and `changeFieldControl` methods of `ContentType` class

## Summary

`widgetNamespace` argument is a string which currently supports `'builtin' or 'extension' or 'app'` as argument but the typing was missing `'app'`due to which I wasn't able to use migrations with typescript.

## Description

Added to desired typings in `configureEntryEditor` and `changeFieldControl` methods of `ContentType` class

## Motivation and Context

With correct typings, I can finally use migrations with typescript which makes them error prone.

### CODE REVIEW

**Comment by electriccode** [comment]
@ruderngespra @Khaledgarbaya @TimBeyer Can any of you please take a look at this? It's just a typing change.

**Comment by electriccode** [comment]
🔔 Gentle reminder to review, @ruderngespra @Khaledgarbaya @TimBeyer @phoebeschmidt @zcei @matthew-contentful @lehnerm

**Comment by ruderngespra** [comment]
>  Gentle reminder to review, @ruderngespra @Khaledgarbaya @TimBeyer @phoebeschmidt @zcei @matthew-contentful @lehnerm

Hey @electriccode, sorry for the late reply!

We had a problem with the test setup for external contributions and therefore could not check your pr. Could you push an empty commit to your branch, e.g. run `commit --allow-empty` on your fork? Thanks!

**Comment by electriccode** [comment]
Thanks @ruderngespra for the response. I have made an empty commit to my fork.

**Comment by ruderngespra** [comment]
Thanks! Unfortunately, we have a problem with the setup that is blocking the pr for now, I will keep you updated.

**Comment by ruderngespra** [comment]
@electriccode Thanks again for the contribution and sorry again for the delay, it should all be available now.

**Pull request merged**
