### PR TITLE
chore(config-tests): refactor config tests

### PR DESCRIPTION
**Pull request by ruderngespra**
As preparation work for https://github.com/contentful/contentful-migration/pull/1096 we need to adjust our tests so that we can correctly document and test when `cmaToken` and `managementToken` should be picked up from `.contentfulrc`.

This is only adding tests and documenting current behavior, but not the fix yet.

### CODE REVIEW

**Comment by Oatelaus** [comment]
@ruderngespra `cmaToken` is "Content **Management Token**" meaning that it's just another way of referring to "managementToken", no?

Cite: https://github.com/contentful/contentful-cli/pull/150#discussion_r297704401

**Comment by marcolink** [comment]
Hey @ruderngespra, should we get it over the finish line?

**Comment by ruderngespra** [comment]
> @ruderngespra `cmaToken` is "Content **Management Token**" meaning that it's just another way of referring to "managementToken", right?
> 
> Cite: [contentful/contentful-cli#150 (comment)](https://github.com/contentful/contentful-cli/pull/150#discussion_r297704401)

Yes, that's correct. Just an unfortunate renaming.

**Review by Vinz93 — APPROVED** [review]
LGTM 🙂

**Pull request merged**
