### PR TITLE
Consistent signature of changeFieldControl() in README, index.d.ts and index.ts

### PR DESCRIPTION
**Pull request by lehnerm**
## Summary

Fixes inconsistency in changeFieldControl signature raised in issue #198

Same as for the sidebar methods, widgetNamespace should always be mandatory and always precede widgetId. This is due to the fact that widgetId is only unique in said namespace.

### CODE REVIEW

**Comment by lehnerm** [comment]
> Thanks for this, @lehnerm.
> 
> A couple of questions I have:
> Any reason we're switching the positions of `widgetId` and `widgetNamespace` vs leaving it the way it is? We'll just need to update the documentation/readme if we left it this way it is. I could be missing.
> 
> Would this be a breaking change given this method is already being used with `widgetId` coming before `widgetNamespace`?

This was missed in the initial implementation, and one of the documentation files was later altered to reflect the wrong underlying signature. All other methods using `widgetNamespace` and `widgetId` have the same argument order.

What do you think? API consistency over backwards compatibility?

**Comment by makinwab** [comment]
> 
> This was missed in the initial implementation, and one of the documentation files was later altered to reflect the wrong underlying signature. All other methods using `widgetNamespace` and `widgetId` have the same argument order.
> 
> What do you think? API consistency over backwards compatibility?

I get it now and good question 🤔. Don't know what the right answer is for this case.
I guess if the change introduced to re-order the parameter list in the doc was reverted then it tells me we wanted to go for consistency 🤷🏽‍♀️.

**Comment by Khaledgarbaya** [comment]
> What do you think? API consistency over backward compatibility?

For now, IMO we should go for backward compatibility

**Comment by ruhkopf** [comment]
Hi there, is there an update on this issue? Seems like typescript migrations using changeFieldControl are currently broken. For example the following produces wrong results: `myType.changeFieldControl('myField', 'builtin', 'singleLine', {})` produces 
```
Update field myField
    - widgetId: "builtin"
    - widgetNamespace: "singleLine"
```

For now I'm doing `myType.changeFieldControl('myField', 'singleLine' as any, 'builtin', {})` but obviously this is a confusing workaround...

**Pull request merged**
