### PR TITLE
feat: Add support for throwing instead of process.exit(1) on errors

### PR DESCRIPTION
**Pull request by charlespwd**
## Summary

When using the package as a library, it's a good idea to throw an error
instead of exiting with code 1. This way the user can recover from the
mistake somehow (e.g. deleting a throwaway environment on during continuous
integration).

This seems like it solves #111 too. 

## Description

- When using the `runMigration` export, make the function throw instead of process.exit(1).
- When using the `default` export, proceed as before by running process.exit(1) on errors. 

## Motivation and Context

I'm making continuous integration scripts that creates and deletes throwaway branches on CircleCI to test that the migration scripts are valid before they are merged. When the migration fails, I would like it to delete the newly created branch. This is currently impossible because this library will `process.exit(1)` for me. 

Actual run-migration code:
```js
async function main() {
  let statusCode = 0;
  try {
    await createEnvironment();
    await runMigrations();
  } catch (e) {
    console.error(e);
    statusCode = 1;
  } finally {
    await deleteEnvironment();
  }

  process.exit(statusCode);
}
```

Without this PR, the code above is unable to execute the `finally` block after errors.  

I'm open to feedback / suggestions on how to improve this.

### CODE REVIEW

**Comment by charlespwd** [comment]
I don't know how to configure the CONTENTFUL_INTEGRATION_* on travis. But the tests pass for me!
https://pastebin.com/raw/4sc5bWAC

**Comment by Khaledgarbaya** [comment]
Hi @charlespwd,
Thank you for the PR, we will do the test locally and come back to you. I am working on improving the integration test situation using fixtures which will solve the testing problem soon.

**Comment by charlespwd** [comment]
Hi @Khaledgarbaya, @axe312ger. Any updates on this? We'd like to use this here at ALDO group. Thanks.

**Comment by Khaledgarbaya** [comment]
Hi @charlespwd I will check this this first thing tomorrow.
Thanks

**Comment by Khaledgarbaya** [comment]
Hi @charlespwd,
First look the PR is looking good but we would like to have some tests for this behaviour. Especially some integration test. You can check the existing tests and copy some code from there to get a boilerplate ready.
Let me know if I can help
Khaled

**Comment by charlespwd** [comment]
Hey @Khaledgarbaya, the e2e tests fail for me on master. Is that normal?

**Comment by charlespwd** [comment]
Well I didn't want to close it.

**Comment by charlespwd** [comment]
OK, I got an e2e test in. Let me know if you need anything else :) 

@Khaledgarbaya @axe312ger

**Comment by Khaledgarbaya** [comment]
available in `v0.11.1`

**Pull request merged**
